configurationset:
  - configuration:
      name: postgresql_config
      uri: postgresql://ep-muddy-limit-a2iyhwrp.eu-central-1.aws.neon.tech/neondb?user=neondb_owner&password=bhFHrX4T6MSp
  - configuration:
      name: edamam
      app_id: b79de582
      app_key: 02d60f96958aaef8c60a3c06db3aed4b
